/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { addPartlistsToState } from "../redux/actions";

function TshirtModel(props) {
  const { dispatch } = props;
  // const group = useRef();
  const { scene } = useGLTF("tshirtModel.glb");
  const partLists = scene.children;

  useEffect(() => {
    dispatch(addPartlistsToState(partLists));
  }, []);

  return partLists.map((part, index) => {
    return (
      <mesh key={index} geometry={part.geometry} material={part.material} />
    );
  });
}
useGLTF.preload("/tshirtModel.glb");
export default TshirtModel;
