/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
// import { TextureLoader, Color } from "three";
// import { useThree } from "@react-three/fiber";
import { addPartlistToState } from "../redux/actions";

function TshirtModel(props) {
  const { dispatch, newPartList } = props;
  const group = useRef();
  const { nodes, scene } = useGLTF("tshirtModel.glb");
  const partList = scene.children;

  useEffect(() => {
    dispatch(addPartlistToState(partList));
  }, []);

  return newPartList.map((part) => {
    return (
      <mesh key={part.name} geometry={part.geometry} material={part.material} />
    );
  });
}
useGLTF.preload("/tshirtModel.glb");
export default TshirtModel;
